### ISSUE TITLE
Allow using input for assert arguments

### ISSUE THREAD

**Issue by R9295** [R9295/parserkiosk#2]
``` yaml
---
type: "SERIALIZE"
tests:
  test_something:
      info: "Example Test"
      input:
        type: "str"
        arg: "hello, world"
      assert:
        func: "assert_list_entries"
       # Allow this
        arg:
            type: "str"
            arg: "hello, world"
```
It should be possible to  use ``input`` in assert's argument. As auto-formatting string or loading file content would help a lot
