### ISSUE TITLE
Allow multiple "args" for input and assert

### ISSUE THREAD

**Issue by R9295** [R9295/parserkiosk#4]
Let's say I want to use a JSON test suite in Lua and the reference is in Python

``` yaml
# test_serialize.yaml
my_test:
    input:
        type: "str"
        arg: '{"hello": "world"}'
    assert:
        func: "assert_dict"
        arg: "{'hello': 'world'}"
```
This would not work for lua as lua has no dictionaries.
Allow something like:
``` yaml
assert:
    func: "assert_dict"
    arg: 
        default: "{'hello': 'world'}"
        <template_name>: <appropriate_language_representation>
```
